captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: D:/go/src/github.com/snowlyg/go-tenancy
wechat-pay:
  state: ""
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
local:
  path: uploads/file
mysql:
  path: ""
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: ""
  password: ""
  pool-size: 0
system:
  level: error
  env: dev
  addr: 8089
  db-type: 
  cache-type:  # redis , local
  admin-preix: /admin 
  client-preix: /merchant 
timer:
  start: false
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
zap:
  level: info
  format: console
  prefix: '[OP-ONLINE]'
  director: log
  link-name: latest_log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true